# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 点---栅格.py
# Created on: 2025-11-20 21:22:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy,os


# Local variables:
root_dir = r"data/yuanshuju"
for root, dirs, files in os.walk(root_dir):
    for file in files:
        print(file)
        # 只处理txt文件
        if file.lower().endswith('.txt'):
            v2020010100_txt = os.path.join(root, file)
            v2020010100_Layer = file.replace('.txt', '')
# v2020010100_txt = "D:\\Fuxiaodi\\###\\广西-结题报告\\朱老师\\研究区降雨数据—调查点位分布\\20z22\\20z22\\2020\\2020010100.txt"
# v2020010100_Layer = "2020010100_Layer"
            c2020010100_FeatureToPoint = "D:\\Fuxiaodi\\###\\广西-结题报告\\朱老师\\GIS\\no.gdb\\c{}_FeatureToPoint".format(v2020010100_Layer)
            Idw_c202001011 = "D:\\Fuxiaodi\\###\\广西-结题报告\\朱老师\\GIS\\no.gdb\\Idw_c{}".format(v2020010100_Layer)
            study_area = "D:\\Fuxiaodi\\###\\广西-结题报告\\朱老师\\GIS\\out\\研究区.shp"
            Extract_Idw_1 = "D:\\Fuxiaodi\\###\\广西-结题报告\\朱老师\\GIS\\20251120.gdb\\Use_rainfall_{}".format(v2020010100_Layer)

            # Process: 创建 XY 事件图层
            arcpy.MakeXYEventLayer_management(v2020010100_txt, "Field9", "Field5", v2020010100_Layer, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;0.001;0.001;IsHighPrecision", "Field21")

            # Process: 要素转点
            arcpy.FeatureToPoint_management(v2020010100_Layer, c2020010100_FeatureToPoint, "CENTROID")

            # Process: 反距离权重法
            tempEnvironment0 = arcpy.env.newPrecision
            arcpy.env.newPrecision = "SINGLE"
            tempEnvironment1 = arcpy.env.autoCommit
            arcpy.env.autoCommit = "1000"
            tempEnvironment2 = arcpy.env.XYResolution
            arcpy.env.XYResolution = ""
            tempEnvironment3 = arcpy.env.processingServerUser
            arcpy.env.processingServerUser = ""
            tempEnvironment4 = arcpy.env.XYDomain
            arcpy.env.XYDomain = ""
            tempEnvironment5 = arcpy.env.processingServerPassword
            arcpy.env.processingServerPassword = ""
            tempEnvironment6 = arcpy.env.scratchWorkspace
            arcpy.env.scratchWorkspace = "D:\\Fuxiaodi\\###\\广西-结题报告\\朱老师\\GIS\\20251120.gdb"
            tempEnvironment7 = arcpy.env.cartographicPartitions
            arcpy.env.cartographicPartitions = ""
            tempEnvironment8 = arcpy.env.terrainMemoryUsage
            arcpy.env.terrainMemoryUsage = "false"
            tempEnvironment9 = arcpy.env.MTolerance
            arcpy.env.MTolerance = ""
            tempEnvironment10 = arcpy.env.compression
            arcpy.env.compression = "LZ77"
            tempEnvironment11 = arcpy.env.coincidentPoints
            arcpy.env.coincidentPoints = "MEAN"
            tempEnvironment12 = arcpy.env.randomGenerator
            arcpy.env.randomGenerator = "0 ACM599"
            tempEnvironment13 = arcpy.env.outputCoordinateSystem
            arcpy.env.outputCoordinateSystem = ""
            tempEnvironment14 = arcpy.env.rasterStatistics
            arcpy.env.rasterStatistics = "STATISTICS 1 1"
            tempEnvironment15 = arcpy.env.ZDomain
            arcpy.env.ZDomain = ""
            tempEnvironment16 = arcpy.env.cellSizeProjectionMethod
            arcpy.env.cellSizeProjectionMethod = "CONVERT_UNITS"
            tempEnvironment17 = arcpy.env.transferDomains
            arcpy.env.transferDomains = "false"
            tempEnvironment18 = arcpy.env.maintainAttachments
            arcpy.env.maintainAttachments = "true"
            tempEnvironment19 = arcpy.env.resamplingMethod
            arcpy.env.resamplingMethod = "NEAREST"
            tempEnvironment20 = arcpy.env.snapRaster
            arcpy.env.snapRaster = ""
            tempEnvironment21 = arcpy.env.projectCompare
            arcpy.env.projectCompare = "NONE"
            tempEnvironment22 = arcpy.env.cartographicCoordinateSystem
            arcpy.env.cartographicCoordinateSystem = tempEnvironment22
            tempEnvironment23 = arcpy.env.configKeyword
            arcpy.env.configKeyword = ""
            tempEnvironment24 = arcpy.env.outputZFlag
            arcpy.env.outputZFlag = "Same As Input"
            tempEnvironment25 = arcpy.env.qualifiedFieldNames
            arcpy.env.qualifiedFieldNames = "true"
            tempEnvironment26 = arcpy.env.tileSize
            arcpy.env.tileSize = "128 128"
            tempEnvironment27 = arcpy.env.parallelProcessingFactor
            arcpy.env.parallelProcessingFactor = ""
            tempEnvironment28 = arcpy.env.pyramid
            arcpy.env.pyramid = "PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP"
            tempEnvironment29 = arcpy.env.referenceScale
            arcpy.env.referenceScale = ""
            tempEnvironment30 = arcpy.env.processingServer
            arcpy.env.processingServer = ""
            tempEnvironment31 = arcpy.env.extent
            arcpy.env.extent = "109.652522 21.885073 111.42598 23.456395"
            tempEnvironment32 = arcpy.env.XYTolerance
            arcpy.env.XYTolerance = ""
            tempEnvironment33 = arcpy.env.tinSaveVersion
            arcpy.env.tinSaveVersion = "CURRENT"
            tempEnvironment34 = arcpy.env.nodata
            arcpy.env.nodata = "NONE"
            tempEnvironment35 = arcpy.env.MDomain
            arcpy.env.MDomain = ""
            tempEnvironment36 = arcpy.env.spatialGrid1
            arcpy.env.spatialGrid1 = "0"
            tempEnvironment37 = arcpy.env.cellSize
            arcpy.env.cellSize = "MAXOF"
            tempEnvironment38 = arcpy.env.outputZValue
            arcpy.env.outputZValue = ""
            tempEnvironment39 = arcpy.env.outputMFlag
            arcpy.env.outputMFlag = "Same As Input"
            tempEnvironment40 = arcpy.env.geographicTransformations
            arcpy.env.geographicTransformations = "NAD_1927_To_NAD_1983_NADCON;NAD_1927_To_NAD_1983_NADCON"
            tempEnvironment41 = arcpy.env.spatialGrid2
            arcpy.env.spatialGrid2 = "0"
            tempEnvironment42 = arcpy.env.ZResolution
            arcpy.env.ZResolution = ""
            tempEnvironment43 = arcpy.env.mask
            arcpy.env.mask = ""
            tempEnvironment44 = arcpy.env.spatialGrid3
            arcpy.env.spatialGrid3 = "0"
            tempEnvironment45 = arcpy.env.maintainSpatialIndex
            arcpy.env.maintainSpatialIndex = "false"
            tempEnvironment46 = arcpy.env.workspace
            arcpy.env.workspace = "D:\\Fuxiaodi\\###\\广西-结题报告\\朱老师\\GIS\\20251120.gdb"
            tempEnvironment47 = arcpy.env.MResolution
            arcpy.env.MResolution = ""
            tempEnvironment48 = arcpy.env.derivedPrecision
            arcpy.env.derivedPrecision = "HIGHEST"
            tempEnvironment49 = arcpy.env.ZTolerance
            arcpy.env.ZTolerance = ""
            arcpy.gp.Idw_sa(c2020010100_FeatureToPoint, "Field21", Idw_c202001011, "6.28528800000001E-03", "2", "VARIABLE 12", "")
            arcpy.env.newPrecision = tempEnvironment0
            arcpy.env.autoCommit = tempEnvironment1
            arcpy.env.XYResolution = tempEnvironment2
            arcpy.env.processingServerUser = tempEnvironment3
            arcpy.env.XYDomain = tempEnvironment4
            arcpy.env.processingServerPassword = tempEnvironment5
            arcpy.env.scratchWorkspace = tempEnvironment6
            arcpy.env.cartographicPartitions = tempEnvironment7
            arcpy.env.terrainMemoryUsage = tempEnvironment8
            arcpy.env.MTolerance = tempEnvironment9
            arcpy.env.compression = tempEnvironment10
            arcpy.env.coincidentPoints = tempEnvironment11
            arcpy.env.randomGenerator = tempEnvironment12
            arcpy.env.outputCoordinateSystem = tempEnvironment13
            arcpy.env.rasterStatistics = tempEnvironment14
            arcpy.env.ZDomain = tempEnvironment15
            arcpy.env.cellSizeProjectionMethod = tempEnvironment16
            arcpy.env.transferDomains = tempEnvironment17
            arcpy.env.maintainAttachments = tempEnvironment18
            arcpy.env.resamplingMethod = tempEnvironment19
            arcpy.env.snapRaster = tempEnvironment20
            arcpy.env.projectCompare = tempEnvironment21
            arcpy.env.cartographicCoordinateSystem = tempEnvironment22
            arcpy.env.configKeyword = tempEnvironment23
            arcpy.env.outputZFlag = tempEnvironment24
            arcpy.env.qualifiedFieldNames = tempEnvironment25
            arcpy.env.tileSize = tempEnvironment26
            arcpy.env.parallelProcessingFactor = tempEnvironment27
            arcpy.env.pyramid = tempEnvironment28
            arcpy.env.referenceScale = tempEnvironment29
            arcpy.env.processingServer = tempEnvironment30
            arcpy.env.extent = tempEnvironment31
            arcpy.env.XYTolerance = tempEnvironment32
            arcpy.env.tinSaveVersion = tempEnvironment33
            arcpy.env.nodata = tempEnvironment34
            arcpy.env.MDomain = tempEnvironment35
            arcpy.env.spatialGrid1 = tempEnvironment36
            arcpy.env.cellSize = tempEnvironment37
            arcpy.env.outputZValue = tempEnvironment38
            arcpy.env.outputMFlag = tempEnvironment39
            arcpy.env.geographicTransformations = tempEnvironment40
            arcpy.env.spatialGrid2 = tempEnvironment41
            arcpy.env.ZResolution = tempEnvironment42
            arcpy.env.mask = tempEnvironment43
            arcpy.env.spatialGrid3 = tempEnvironment44
            arcpy.env.maintainSpatialIndex = tempEnvironment45
            arcpy.env.workspace = tempEnvironment46
            arcpy.env.MResolution = tempEnvironment47
            arcpy.env.derivedPrecision = tempEnvironment48
            arcpy.env.ZTolerance = tempEnvironment49

            # Process: 按掩膜提取
            tempEnvironment0 = arcpy.env.newPrecision
            arcpy.env.newPrecision = "SINGLE"
            tempEnvironment1 = arcpy.env.autoCommit
            arcpy.env.autoCommit = "1000"
            tempEnvironment2 = arcpy.env.XYResolution
            arcpy.env.XYResolution = ""
            tempEnvironment3 = arcpy.env.processingServerUser
            arcpy.env.processingServerUser = ""
            tempEnvironment4 = arcpy.env.XYDomain
            arcpy.env.XYDomain = ""
            tempEnvironment5 = arcpy.env.processingServerPassword
            arcpy.env.processingServerPassword = ""
            tempEnvironment6 = arcpy.env.scratchWorkspace
            arcpy.env.scratchWorkspace = "D:\\Fuxiaodi\\###\\广西-结题报告\\朱老师\\GIS\\20251120.gdb"
            tempEnvironment7 = arcpy.env.cartographicPartitions
            arcpy.env.cartographicPartitions = ""
            tempEnvironment8 = arcpy.env.terrainMemoryUsage
            arcpy.env.terrainMemoryUsage = "false"
            tempEnvironment9 = arcpy.env.MTolerance
            arcpy.env.MTolerance = ""
            tempEnvironment10 = arcpy.env.compression
            arcpy.env.compression = "LZ77"
            tempEnvironment11 = arcpy.env.coincidentPoints
            arcpy.env.coincidentPoints = "MEAN"
            tempEnvironment12 = arcpy.env.randomGenerator
            arcpy.env.randomGenerator = "0 ACM599"
            tempEnvironment13 = arcpy.env.outputCoordinateSystem
            arcpy.env.outputCoordinateSystem = ""
            tempEnvironment14 = arcpy.env.rasterStatistics
            arcpy.env.rasterStatistics = "STATISTICS 1 1"
            tempEnvironment15 = arcpy.env.ZDomain
            arcpy.env.ZDomain = ""
            tempEnvironment16 = arcpy.env.cellSizeProjectionMethod
            arcpy.env.cellSizeProjectionMethod = "CONVERT_UNITS"
            tempEnvironment17 = arcpy.env.transferDomains
            arcpy.env.transferDomains = "false"
            tempEnvironment18 = arcpy.env.maintainAttachments
            arcpy.env.maintainAttachments = "true"
            tempEnvironment19 = arcpy.env.resamplingMethod
            arcpy.env.resamplingMethod = "NEAREST"
            tempEnvironment20 = arcpy.env.snapRaster
            arcpy.env.snapRaster = ""
            tempEnvironment21 = arcpy.env.projectCompare
            arcpy.env.projectCompare = "NONE"
            tempEnvironment22 = arcpy.env.cartographicCoordinateSystem
            arcpy.env.cartographicCoordinateSystem = tempEnvironment22
            tempEnvironment23 = arcpy.env.configKeyword
            arcpy.env.configKeyword = ""
            tempEnvironment24 = arcpy.env.outputZFlag
            arcpy.env.outputZFlag = "Same As Input"
            tempEnvironment25 = arcpy.env.qualifiedFieldNames
            arcpy.env.qualifiedFieldNames = "true"
            tempEnvironment26 = arcpy.env.tileSize
            arcpy.env.tileSize = "128 128"
            tempEnvironment27 = arcpy.env.parallelProcessingFactor
            arcpy.env.parallelProcessingFactor = ""
            tempEnvironment28 = arcpy.env.pyramid
            arcpy.env.pyramid = "PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP"
            tempEnvironment29 = arcpy.env.referenceScale
            arcpy.env.referenceScale = ""
            tempEnvironment30 = arcpy.env.processingServer
            arcpy.env.processingServer = ""
            tempEnvironment31 = arcpy.env.extent
            arcpy.env.extent = "DEFAULT"
            tempEnvironment32 = arcpy.env.XYTolerance
            arcpy.env.XYTolerance = ""
            tempEnvironment33 = arcpy.env.tinSaveVersion
            arcpy.env.tinSaveVersion = "CURRENT"
            tempEnvironment34 = arcpy.env.nodata
            arcpy.env.nodata = "NONE"
            tempEnvironment35 = arcpy.env.MDomain
            arcpy.env.MDomain = ""
            tempEnvironment36 = arcpy.env.spatialGrid1
            arcpy.env.spatialGrid1 = "0"
            tempEnvironment37 = arcpy.env.cellSize
            arcpy.env.cellSize = "MAXOF"
            tempEnvironment38 = arcpy.env.outputZValue
            arcpy.env.outputZValue = ""
            tempEnvironment39 = arcpy.env.outputMFlag
            arcpy.env.outputMFlag = "Same As Input"
            tempEnvironment40 = arcpy.env.geographicTransformations
            arcpy.env.geographicTransformations = "NAD_1927_To_NAD_1983_NADCON"
            tempEnvironment41 = arcpy.env.spatialGrid2
            arcpy.env.spatialGrid2 = "0"
            tempEnvironment42 = arcpy.env.ZResolution
            arcpy.env.ZResolution = ""
            tempEnvironment43 = arcpy.env.mask
            arcpy.env.mask = ""
            tempEnvironment44 = arcpy.env.spatialGrid3
            arcpy.env.spatialGrid3 = "0"
            tempEnvironment45 = arcpy.env.maintainSpatialIndex
            arcpy.env.maintainSpatialIndex = "false"
            tempEnvironment46 = arcpy.env.workspace
            arcpy.env.workspace = "D:\\Fuxiaodi\\###\\广西-结题报告\\朱老师\\GIS\\20251120.gdb"
            tempEnvironment47 = arcpy.env.MResolution
            arcpy.env.MResolution = ""
            tempEnvironment48 = arcpy.env.derivedPrecision
            arcpy.env.derivedPrecision = "HIGHEST"
            tempEnvironment49 = arcpy.env.ZTolerance
            arcpy.env.ZTolerance = ""
            arcpy.gp.ExtractByMask_sa(Idw_c202001011, study_area, Extract_Idw_1)
            arcpy.env.newPrecision = tempEnvironment0
            arcpy.env.autoCommit = tempEnvironment1
            arcpy.env.XYResolution = tempEnvironment2
            arcpy.env.processingServerUser = tempEnvironment3
            arcpy.env.XYDomain = tempEnvironment4
            arcpy.env.processingServerPassword = tempEnvironment5
            arcpy.env.scratchWorkspace = tempEnvironment6
            arcpy.env.cartographicPartitions = tempEnvironment7
            arcpy.env.terrainMemoryUsage = tempEnvironment8
            arcpy.env.MTolerance = tempEnvironment9
            arcpy.env.compression = tempEnvironment10
            arcpy.env.coincidentPoints = tempEnvironment11
            arcpy.env.randomGenerator = tempEnvironment12
            arcpy.env.outputCoordinateSystem = tempEnvironment13
            arcpy.env.rasterStatistics = tempEnvironment14
            arcpy.env.ZDomain = tempEnvironment15
            arcpy.env.cellSizeProjectionMethod = tempEnvironment16
            arcpy.env.transferDomains = tempEnvironment17
            arcpy.env.maintainAttachments = tempEnvironment18
            arcpy.env.resamplingMethod = tempEnvironment19
            arcpy.env.snapRaster = tempEnvironment20
            arcpy.env.projectCompare = tempEnvironment21
            arcpy.env.cartographicCoordinateSystem = tempEnvironment22
            arcpy.env.configKeyword = tempEnvironment23
            arcpy.env.outputZFlag = tempEnvironment24
            arcpy.env.qualifiedFieldNames = tempEnvironment25
            arcpy.env.tileSize = tempEnvironment26
            arcpy.env.parallelProcessingFactor = tempEnvironment27
            arcpy.env.pyramid = tempEnvironment28
            arcpy.env.referenceScale = tempEnvironment29
            arcpy.env.processingServer = tempEnvironment30
            arcpy.env.extent = tempEnvironment31
            arcpy.env.XYTolerance = tempEnvironment32
            arcpy.env.tinSaveVersion = tempEnvironment33
            arcpy.env.nodata = tempEnvironment34
            arcpy.env.MDomain = tempEnvironment35
            arcpy.env.spatialGrid1 = tempEnvironment36
            arcpy.env.cellSize = tempEnvironment37
            arcpy.env.outputZValue = tempEnvironment38
            arcpy.env.outputMFlag = tempEnvironment39
            arcpy.env.geographicTransformations = tempEnvironment40
            arcpy.env.spatialGrid2 = tempEnvironment41
            arcpy.env.ZResolution = tempEnvironment42
            arcpy.env.mask = tempEnvironment43
            arcpy.env.spatialGrid3 = tempEnvironment44
            arcpy.env.maintainSpatialIndex = tempEnvironment45
            arcpy.env.workspace = tempEnvironment46
            arcpy.env.MResolution = tempEnvironment47
            arcpy.env.derivedPrecision = tempEnvironment48
            arcpy.env.ZTolerance = tempEnvironment49

