# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 2.py
# Created on: 2025-08-09 17:18:35.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------
import os

# Set the necessary product code
# import arcinfo

# Import arcpy module
import arcpy

# Local variables:
grid1km_gd_rain_xls = "C:/Users/ASUS/Desktop/gis/data"

for file in os.listdir(grid1km_gd_rain_xls):
    file_path = os.path.join(grid1km_gd_rain_xls, file)

    v_name_ = "D:/Fuxiaodi/朱老师-广东浅层滑坡/20250808/0808.gdb/"+file.replace('.xlsx', '')
    v_name__Layer = file.replace('.xls', '')
    v_name__point = "D:/Fuxiaodi/朱老师-广东浅层滑坡/20250808/0808.gdb/"+file.replace('.xlsx', '_point')
    print(file_path, v_name__point)

    # Process: Excel 转表
    arcpy.ExcelToTable_conversion(file_path, v_name_)

    # Process: 创建 XY 事件图层
    arcpy.MakeXYEventLayer_management(v_name_, "lon", "lat", v_name__Layer,
                                      "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;0.001;0.001;IsHighPrecision",
                                      "Rain")

    # Process: 要素转点
    arcpy.FeatureToPoint_management(v_name__Layer, v_name__point, "CENTROID")