# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 批量点转栅格.py
# Created on: 2025-08-10 08:31:53.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy,os


# Local variables:

grid1km_gd_rain_xls = "C:/Users/ASUS/Desktop/gis/data"

for file in os.listdir(grid1km_gd_rain_xls):
    name = file.replace('.xlsx', '_point').replace('grid1km_obs_rain_', '').replace('_point', '')
    print(name)

    grid1km_obs_rain_2024060900_point = "D:\\Fuxiaodi\\朱老师-广东浅层滑坡\\20250808\\0808.gdb\\grid1km_obs_rain_{}_point".format(name)
    rain_1km_2024060900 = "D:\\Fuxiaodi\\朱老师-广东浅层滑坡\\20250808\\0808.gdb\\rain_1km_{}".format(name)
    use = "D:\\Fuxiaodi\\朱老师-广东浅层滑坡\\20250808\\use.gdb\\rain_1km_{}".format(name)

    if arcpy.Exists(rain_1km_2024060900):
        print("目标文件已存在，跳过处理: {}\n".format(rain_1km_2024060900))
        continue

    # Process: 点转栅格
    arcpy.PointToRaster_conversion(grid1km_obs_rain_2024060900_point, "Rain", rain_1km_2024060900, "MOST_FREQUENT", "NONE", "0.021")
