# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 批量投影.py
# Created on: 2025-08-10 11:27:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------
import os

# Import arcpy module
import arcpy

grid1km_gd_rain_xls = "C:/Users/ASUS/Desktop/gis/data"

for file in os.listdir(grid1km_gd_rain_xls):
    name = file.replace('.xlsx', '_point').replace('grid1km_obs_rain_', '').replace('_point', '')
    print(name)

    # Local variables:
    rain_1km_2024061623__2_ = "D:\\Fuxiaodi\\朱老师-广东浅层滑坡\\20250808\\0808.gdb\\rain_1km_{}".format(name)
    rain_1km_2024061623_Project = "D:\\Fuxiaodi\\朱老师-广东浅层滑坡\\20250808\\0808.gdb\\gd_rain_1km_{}".format(name)
    rain_1km_2024061623 = "属性\\降雨\\rain_1km_{}".format(name)

    # Process: 投影栅格
    tempEnvironment0 = arcpy.env.newPrecision
    arcpy.env.newPrecision = "SINGLE"
    tempEnvironment1 = arcpy.env.autoCommit
    arcpy.env.autoCommit = "1000"
    tempEnvironment2 = arcpy.env.XYResolution
    arcpy.env.XYResolution = ""
    tempEnvironment3 = arcpy.env.processingServerUser
    arcpy.env.processingServerUser = ""
    tempEnvironment4 = arcpy.env.XYDomain
    arcpy.env.XYDomain = ""
    tempEnvironment5 = arcpy.env.processingServerPassword
    arcpy.env.processingServerPassword = ""
    tempEnvironment6 = arcpy.env.scratchWorkspace
    arcpy.env.scratchWorkspace = "D:\\Fuxiaodi\\朱老师-广东浅层滑坡\\20250808\\0808.gdb"
    tempEnvironment7 = arcpy.env.cartographicPartitions
    arcpy.env.cartographicPartitions = ""
    tempEnvironment8 = arcpy.env.terrainMemoryUsage
    arcpy.env.terrainMemoryUsage = "false"
    tempEnvironment9 = arcpy.env.MTolerance
    arcpy.env.MTolerance = ""
    tempEnvironment10 = arcpy.env.compression
    arcpy.env.compression = "LZ77"
    tempEnvironment11 = arcpy.env.coincidentPoints
    arcpy.env.coincidentPoints = "MEAN"
    tempEnvironment12 = arcpy.env.randomGenerator
    arcpy.env.randomGenerator = "0 ACM599"
    tempEnvironment13 = arcpy.env.outputCoordinateSystem
    arcpy.env.outputCoordinateSystem = ""
    tempEnvironment14 = arcpy.env.rasterStatistics
    arcpy.env.rasterStatistics = "STATISTICS 1 1"
    tempEnvironment15 = arcpy.env.ZDomain
    arcpy.env.ZDomain = ""
    tempEnvironment16 = arcpy.env.cellSizeProjectionMethod
    arcpy.env.cellSizeProjectionMethod = "CONVERT_UNITS"
    tempEnvironment17 = arcpy.env.transferDomains
    arcpy.env.transferDomains = "false"
    tempEnvironment18 = arcpy.env.maintainAttachments
    arcpy.env.maintainAttachments = "true"
    tempEnvironment19 = arcpy.env.resamplingMethod
    arcpy.env.resamplingMethod = "NEAREST"
    tempEnvironment20 = arcpy.env.snapRaster
    arcpy.env.snapRaster = ""
    tempEnvironment21 = arcpy.env.projectCompare
    arcpy.env.projectCompare = "NONE"
    tempEnvironment22 = arcpy.env.cartographicCoordinateSystem
    arcpy.env.cartographicCoordinateSystem = "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],VERTCS['EGM96_Geoid',VDATUM['EGM96_Geoid'],PARAMETER['Vertical_Shift',0.0],PARAMETER['Direction',1.0],UNIT['Meter',1.0]]"
    tempEnvironment23 = arcpy.env.configKeyword
    arcpy.env.configKeyword = ""
    tempEnvironment24 = arcpy.env.outputZFlag
    arcpy.env.outputZFlag = "Same As Input"
    tempEnvironment25 = arcpy.env.qualifiedFieldNames
    arcpy.env.qualifiedFieldNames = "true"
    tempEnvironment26 = arcpy.env.tileSize
    arcpy.env.tileSize = "128 128"
    tempEnvironment27 = arcpy.env.parallelProcessingFactor
    arcpy.env.parallelProcessingFactor = ""
    tempEnvironment28 = arcpy.env.pyramid
    arcpy.env.pyramid = "PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP"
    tempEnvironment29 = arcpy.env.referenceScale
    arcpy.env.referenceScale = ""
    tempEnvironment30 = arcpy.env.processingServer
    arcpy.env.processingServer = ""
    tempEnvironment31 = arcpy.env.extent
    arcpy.env.extent = "DEFAULT"
    tempEnvironment32 = arcpy.env.XYTolerance
    arcpy.env.XYTolerance = ""
    tempEnvironment33 = arcpy.env.tinSaveVersion
    arcpy.env.tinSaveVersion = "CURRENT"
    tempEnvironment34 = arcpy.env.nodata
    arcpy.env.nodata = "NONE"
    tempEnvironment35 = arcpy.env.MDomain
    arcpy.env.MDomain = ""
    tempEnvironment36 = arcpy.env.spatialGrid1
    arcpy.env.spatialGrid1 = "0"
    tempEnvironment37 = arcpy.env.cellSize
    arcpy.env.cellSize = "MAXOF"
    tempEnvironment38 = arcpy.env.outputZValue
    arcpy.env.outputZValue = ""
    tempEnvironment39 = arcpy.env.outputMFlag
    arcpy.env.outputMFlag = "Same As Input"
    tempEnvironment40 = arcpy.env.geographicTransformations
    arcpy.env.geographicTransformations = "NAD_1927_To_NAD_1983_NADCON"
    tempEnvironment41 = arcpy.env.spatialGrid2
    arcpy.env.spatialGrid2 = "0"
    tempEnvironment42 = arcpy.env.ZResolution
    arcpy.env.ZResolution = ""
    tempEnvironment43 = arcpy.env.mask
    arcpy.env.mask = ""
    tempEnvironment44 = arcpy.env.spatialGrid3
    arcpy.env.spatialGrid3 = "0"
    tempEnvironment45 = arcpy.env.maintainSpatialIndex
    arcpy.env.maintainSpatialIndex = "false"
    tempEnvironment46 = arcpy.env.workspace
    arcpy.env.workspace = "D:\\Fuxiaodi\\朱老师-广东浅层滑坡\\20250808\\0808.gdb"
    tempEnvironment47 = arcpy.env.MResolution
    arcpy.env.MResolution = ""
    tempEnvironment48 = arcpy.env.derivedPrecision
    arcpy.env.derivedPrecision = "HIGHEST"
    tempEnvironment49 = arcpy.env.ZTolerance
    arcpy.env.ZTolerance = ""
    arcpy.ProjectRaster_management(rain_1km_2024061623__2_, rain_1km_2024061623_Project, "PROJCS['WGS_1984_UTM_Zone_49N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',111.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "NEAREST", "2288.4290436656 2288.4290436656", "", "", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "NO_VERTICAL")
    arcpy.env.newPrecision = tempEnvironment0
    arcpy.env.autoCommit = tempEnvironment1
    arcpy.env.XYResolution = tempEnvironment2
    arcpy.env.processingServerUser = tempEnvironment3
    arcpy.env.XYDomain = tempEnvironment4
    arcpy.env.processingServerPassword = tempEnvironment5
    arcpy.env.scratchWorkspace = tempEnvironment6
    arcpy.env.cartographicPartitions = tempEnvironment7
    arcpy.env.terrainMemoryUsage = tempEnvironment8
    arcpy.env.MTolerance = tempEnvironment9
    arcpy.env.compression = tempEnvironment10
    arcpy.env.coincidentPoints = tempEnvironment11
    arcpy.env.randomGenerator = tempEnvironment12
    arcpy.env.outputCoordinateSystem = tempEnvironment13
    arcpy.env.rasterStatistics = tempEnvironment14
    arcpy.env.ZDomain = tempEnvironment15
    arcpy.env.cellSizeProjectionMethod = tempEnvironment16
    arcpy.env.transferDomains = tempEnvironment17
    arcpy.env.maintainAttachments = tempEnvironment18
    arcpy.env.resamplingMethod = tempEnvironment19
    arcpy.env.snapRaster = tempEnvironment20
    arcpy.env.projectCompare = tempEnvironment21
    arcpy.env.cartographicCoordinateSystem = tempEnvironment22
    arcpy.env.configKeyword = tempEnvironment23
    arcpy.env.outputZFlag = tempEnvironment24
    arcpy.env.qualifiedFieldNames = tempEnvironment25
    arcpy.env.tileSize = tempEnvironment26
    arcpy.env.parallelProcessingFactor = tempEnvironment27
    arcpy.env.pyramid = tempEnvironment28
    arcpy.env.referenceScale = tempEnvironment29
    arcpy.env.processingServer = tempEnvironment30
    arcpy.env.extent = tempEnvironment31
    arcpy.env.XYTolerance = tempEnvironment32
    arcpy.env.tinSaveVersion = tempEnvironment33
    arcpy.env.nodata = tempEnvironment34
    arcpy.env.MDomain = tempEnvironment35
    arcpy.env.spatialGrid1 = tempEnvironment36
    arcpy.env.cellSize = tempEnvironment37
    arcpy.env.outputZValue = tempEnvironment38
    arcpy.env.outputMFlag = tempEnvironment39
    arcpy.env.geographicTransformations = tempEnvironment40
    arcpy.env.spatialGrid2 = tempEnvironment41
    arcpy.env.ZResolution = tempEnvironment42
    arcpy.env.mask = tempEnvironment43
    arcpy.env.spatialGrid3 = tempEnvironment44
    arcpy.env.maintainSpatialIndex = tempEnvironment45
    arcpy.env.workspace = tempEnvironment46
    arcpy.env.MResolution = tempEnvironment47
    arcpy.env.derivedPrecision = tempEnvironment48
    arcpy.env.ZTolerance = tempEnvironment49

